package com.projeto2.view;

import javax.swing.ImageIcon;

/**
 *
 * @author Igor J Rodrigues
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        ImageIcon icon = new ImageIcon("resources/lunch.png");
        this.setIconImage(icon.getImage());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuVer = new javax.swing.JMenu();
        jMenuItemVerPedidos = new javax.swing.JMenuItem();
        jMenuAdicionar = new javax.swing.JMenu();
        jMenuItemAdicionarPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LunchApp");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("frameInicial"); // NOI18N
        setResizable(false);

        jMenuVer.setText("Ver");

        jMenuItemVerPedidos.setText("Ver Pedidos");
        jMenuVer.add(jMenuItemVerPedidos);

        jMenuBar.add(jMenuVer);

        jMenuAdicionar.setText("Adicionar");
        jMenuAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdicionarActionPerformed(evt);
            }
        });

        jMenuItemAdicionarPedido.setText("Adicionar Pedido");
        jMenuAdicionar.add(jMenuItemAdicionarPedido);

        jMenuBar.add(jMenuAdicionar);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAdicionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAdicionar;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemAdicionarPedido;
    private javax.swing.JMenuItem jMenuItemVerPedidos;
    private javax.swing.JMenu jMenuVer;
    // End of variables declaration//GEN-END:variables
}
